version: "2"

issues:
  max-same-issues: 3

formatters:
  enable:
    - gofmt
    - gci
    - golines
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tiamiru/omnistash)
    golines:
      max-len: 120
      shorten-comments: true
      chain-split-dots: true

linters:
  default: all
  disable:
    - gomodguard      # deprecated
    - exhaustruct
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - testpackage
    - revive

  exclusions:
    rules:
    - text: '"OCI-(Tag|Subject)" is not canonical'
      linters: [ canonicalheader ]
    - text: 'should have a package comment'
      linters: [ revive ]
    - path: '_test\.go'
      linters:
        - errcheck
        - funlen
        - goconst
    - path: 'blobstoretest/'
      linters:
        - goconst
        - mnd

  settings:
    mnd:
      ignored-functions:
        - os.MkdirAll
        - os.Mkdir
        - os.OpenFile
        - os.Chmod
        - os.WriteFile
    interfacebloat:
      max: 16
    cyclop:
      max-complexity: 30
      package-average: 10
    depguard:
      rules:
        deprecated:
          files:
            - "$all"
          deny:
            - pkg: io/ioutil
              desc: Deprecated since Go 1.16. Use io and os packages instead
